export const ActionTypes = {
	EMAIL_CHANGED: 'EMAIL_CHANGED',
	PASSWORD_CHANGED: 'PASSWORD_CHANGED',
	LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
	LOGIN_USER_FAIL: 'LOGIN_USER_FAIL',
	LOGIN_USER: 'LOGIN_USER'
};
